module_name: EU Cookie Consent
compatible_versions: 1.0.0+
author: thirty bees
category: front office
tags:
  - eu cookie
  - eu legal
  - cookie
  - eu law
  - eucookieconsent
description_short: The EU cookie consent module ask customers if they consent to being cookied.
description: description.md
images:
  - image-1.png
license: AFL